services:
  - type: web
    name: webtoepub-telegram-bot
    env: python
    buildCommand: "./build.sh"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.5
      # Tell the build script AND the running app where to store/find the browsers
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/.playwright
